/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AboutHowItWorksRouteImport } from './routes/about.how-it-works'
import { Route as ApiGuideRouteImport } from './routes/api/guide'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesSlugRouteImport } from './routes/classes.$slug'
import { Route as PractitionersIndexRouteImport } from './routes/practitioners.index'
import { Route as PractitionersSlugRouteImport } from './routes/practitioners.$slug'
import { Route as PractitionersApplyRouteImport } from './routes/practitioners.apply'
import { Route as ShoppeIndexRouteImport } from './routes/shoppe.index'
import { Route as ShoppeSlugRouteImport } from './routes/shoppe.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHowItWorksRoute = AboutHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AboutRoute,
} as any)
const ApiGuideRoute = ApiGuideRouteImport.update({
  id: '/api/guide',
  path: '/api/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesSlugRoute = ClassesSlugRouteImport.update({
  id: '/classes/$slug',
  path: '/classes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionersIndexRoute = PractitionersIndexRouteImport.update({
  id: '/practitioners/',
  path: '/practitioners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionersSlugRoute = PractitionersSlugRouteImport.update({
  id: '/practitioners/$slug',
  path: '/practitioners/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionersApplyRoute = PractitionersApplyRouteImport.update({
  id: '/practitioners/apply',
  path: '/practitioners/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppeIndexRoute = ShoppeIndexRouteImport.update({
  id: '/shoppe/',
  path: '/shoppe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppeSlugRoute = ShoppeSlugRouteImport.update({
  id: '/shoppe/$slug',
  path: '/shoppe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/how-it-works': typeof AboutHowItWorksRoute
  '/api/guide': typeof ApiGuideRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/practitioners/$slug': typeof PractitionersSlugRoute
  '/practitioners/apply': typeof PractitionersApplyRoute
  '/shoppe/$slug': typeof ShoppeSlugRoute
  '/classes/': typeof ClassesIndexRoute
  '/practitioners/': typeof PractitionersIndexRoute
  '/shoppe/': typeof ShoppeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/how-it-works': typeof AboutHowItWorksRoute
  '/api/guide': typeof ApiGuideRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/practitioners/$slug': typeof PractitionersSlugRoute
  '/practitioners/apply': typeof PractitionersApplyRoute
  '/shoppe/$slug': typeof ShoppeSlugRoute
  '/classes': typeof ClassesIndexRoute
  '/practitioners': typeof PractitionersIndexRoute
  '/shoppe': typeof ShoppeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/how-it-works': typeof AboutHowItWorksRoute
  '/api/guide': typeof ApiGuideRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/practitioners/$slug': typeof PractitionersSlugRoute
  '/practitioners/apply': typeof PractitionersApplyRoute
  '/shoppe/$slug': typeof ShoppeSlugRoute
  '/classes/': typeof ClassesIndexRoute
  '/practitioners/': typeof PractitionersIndexRoute
  '/shoppe/': typeof ShoppeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/membership'
    | '/privacy'
    | '/terms'
    | '/about/how-it-works'
    | '/api/guide'
    | '/classes/$slug'
    | '/practitioners/$slug'
    | '/practitioners/apply'
    | '/shoppe/$slug'
    | '/classes/'
    | '/practitioners/'
    | '/shoppe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/membership'
    | '/privacy'
    | '/terms'
    | '/about/how-it-works'
    | '/api/guide'
    | '/classes/$slug'
    | '/practitioners/$slug'
    | '/practitioners/apply'
    | '/shoppe/$slug'
    | '/classes'
    | '/practitioners'
    | '/shoppe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/membership'
    | '/privacy'
    | '/terms'
    | '/about/how-it-works'
    | '/api/guide'
    | '/classes/$slug'
    | '/practitioners/$slug'
    | '/practitioners/apply'
    | '/shoppe/$slug'
    | '/classes/'
    | '/practitioners/'
    | '/shoppe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiGuideRoute: typeof ApiGuideRoute
  ClassesSlugRoute: typeof ClassesSlugRoute
  PractitionersSlugRoute: typeof PractitionersSlugRoute
  PractitionersApplyRoute: typeof PractitionersApplyRoute
  ShoppeSlugRoute: typeof ShoppeSlugRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  PractitionersIndexRoute: typeof PractitionersIndexRoute
  ShoppeIndexRoute: typeof ShoppeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/how-it-works': {
      id: '/about/how-it-works'
      path: '/how-it-works'
      fullPath: '/about/how-it-works'
      preLoaderRoute: typeof AboutHowItWorksRouteImport
      parentRoute: typeof AboutRoute
    }
    '/api/guide': {
      id: '/api/guide'
      path: '/api/guide'
      fullPath: '/api/guide'
      preLoaderRoute: typeof ApiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$slug': {
      id: '/classes/$slug'
      path: '/classes/$slug'
      fullPath: '/classes/$slug'
      preLoaderRoute: typeof ClassesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioners/': {
      id: '/practitioners/'
      path: '/practitioners'
      fullPath: '/practitioners/'
      preLoaderRoute: typeof PractitionersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioners/$slug': {
      id: '/practitioners/$slug'
      path: '/practitioners/$slug'
      fullPath: '/practitioners/$slug'
      preLoaderRoute: typeof PractitionersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioners/apply': {
      id: '/practitioners/apply'
      path: '/practitioners/apply'
      fullPath: '/practitioners/apply'
      preLoaderRoute: typeof PractitionersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoppe/': {
      id: '/shoppe/'
      path: '/shoppe'
      fullPath: '/shoppe/'
      preLoaderRoute: typeof ShoppeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoppe/$slug': {
      id: '/shoppe/$slug'
      path: '/shoppe/$slug'
      fullPath: '/shoppe/$slug'
      preLoaderRoute: typeof ShoppeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutHowItWorksRoute: typeof AboutHowItWorksRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutHowItWorksRoute: AboutHowItWorksRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiGuideRoute: ApiGuideRoute,
  ClassesSlugRoute: ClassesSlugRoute,
  PractitionersSlugRoute: PractitionersSlugRoute,
  PractitionersApplyRoute: PractitionersApplyRoute,
  ShoppeSlugRoute: ShoppeSlugRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  PractitionersIndexRoute: PractitionersIndexRoute,
  ShoppeIndexRoute: ShoppeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
