/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesSlugRouteImport } from './routes/classes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesSlugRoute = ClassesSlugRouteImport.update({
  id: '/classes/$slug',
  path: '/classes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/classes/': typeof ClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/classes': typeof ClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/classes/': typeof ClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/classes/$slug' | '/classes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/classes/$slug' | '/classes'
  id: '__root__' | '/' | '/classes/$slug' | '/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesSlugRoute: typeof ClassesSlugRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$slug': {
      id: '/classes/$slug'
      path: '/classes/$slug'
      fullPath: '/classes/$slug'
      preLoaderRoute: typeof ClassesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesSlugRoute: ClassesSlugRoute,
  ClassesIndexRoute: ClassesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
